import os
import sys
import json
import unittest
from pathlib import Path

# Add project root to path
ROOT_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

from backend.app import create_app
from backend.utils.db import get_db

CLIMATE_CHANGE_ARTICLE = """
Climate Change and Global Warming Overview
Climate change refers to long-term shifts in temperatures and weather patterns across the globe. Since the 1800s, human activities have been the primary driver of climate change, primarily due to burning fossil fuels like coal, oil, and natural gas.

Greenhouse Gases and Sources of Emissions
Burning fossil fuels produces greenhouse gas emissions that act like a blanket wrapped around the Earth, trapping solar heat and driving atmospheric temperatures upward. The main greenhouse gases responsible for global warming include carbon dioxide (CO2) and methane (CH4). Carbon dioxide is released through the combustion of gasoline for road transportation, coal for electrical generation and home heating, and industrial manufacturing. Clearing land and cutting down forests (deforestation) also releases massive amounts of sequestered carbon dioxide into the atmosphere. Methane emissions are heavily generated by livestock agriculture, rice cultivation, landfills, and leaks from oil and natural gas operations.

Key Contributing Sectors
Energy production, industrial manufacturing, global transport, commercial buildings, intensive agriculture, and land use changes are among the principal sectors emitting greenhouse gases into the troposphere.

Observed Consequences and Global Impacts
The consequences of accelerating climate change include prolonged droughts, severe heat waves, changing precipitation patterns, catastrophic wildfires, shrinking polar ice sheets, melting mountain glaciers, and rising global sea levels. Coastal flooding and storm surges threaten island nations and low-lying coastal cities. Extreme weather patterns disrupt global agriculture, reducing crop yields and destabilizing food supplies. Furthermore, rapid ecological shifts lead to habitat destruction and severe losses in global biodiversity.

Mitigation and Renewable Solutions
Mitigating the most catastrophic impacts of climate change requires shifting energy production away from carbon-intensive fossil fuels toward clean, renewable energy sources such as solar, wind, geothermal, and hydroelectric power. Improving energy efficiency, reforestation, sustainable agricultural practices, and international policy cooperation are crucial components in stabilizing global temperature anomalies.
"""

class QuizGenAITestSuite(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.app = create_app()
        cls.client = cls.app.test_client()
        cls.db = get_db()

    def test_00_health_check(self):
        """Test health endpoint."""
        res = self.client.get("/api/health")
        self.assertEqual(res.status_code, 200)
        data = res.get_json()
        self.assertEqual(data.get("status"), "ok")
        self.assertEqual(data.get("app"), "QuizGen AI")

    def test_01_user_registration_and_login(self):
        """Test user registration, JWT generation, and profile fetch."""
        reg_payload = {
            "name": "Alice Johnson",
            "email": "alice.test@university.edu",
            "password": "password123",
            "confirm_password": "password123",
            "role": "student"
        }
        res = self.client.post("/api/auth/register", json=reg_payload)
        self.assertIn(res.status_code, (201, 409))
        
        login_payload = {
            "email": "alice.test@university.edu",
            "password": "password123"
        }
        res = self.client.post("/api/auth/login", json=login_payload)
        self.assertEqual(res.status_code, 200)
        data = res.get_json()
        self.assertIn("token", data)
        token_a = data["token"]

        res = self.client.get("/api/auth/me", headers={"Authorization": f"Bearer {token_a}"})
        self.assertEqual(res.status_code, 200)
        me_data = res.get_json()
        self.assertEqual(me_data["user"]["email"], "alice.test@university.edu")

    def test_02_scenario_1_pdf_upload_topic_supervised_learning(self):
        """Upload Machine_Learning_Notes.pdf, Topic: Supervised Learning, 10 Questions."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token_a = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token_a}"}

        pdf_path = os.path.join(ROOT_DIR, "sample_data", "Machine_Learning_Notes.pdf")
        self.assertTrue(os.path.exists(pdf_path), "Sample PDF should exist")

        with open(pdf_path, "rb") as f:
            data = {
                "file": (f, "Machine_Learning_Notes.pdf"),
                "topic": "Supervised Learning",
                "num_questions": 10,
                "difficulty": "medium",
                "question_types": json.dumps(["mcq", "true_false", "short_answer"])
            }
            res = self.client.post("/api/quizzes/generate", data=data, content_type="multipart/form-data", headers=headers)

        self.assertIn(res.status_code, (200, 201))
        res_data = res.get_json()
        self.assertIn("quiz", res_data)
        quiz = res_data["quiz"]
        self.assertEqual(len(quiz["questions"]), 10)

        for q in quiz["questions"]:
            self.assertIn("source_page", q)
            self.assertIn("source_text", q)
            self.assertIn(q["type"], ["mcq", "true_false", "short_answer"])

    def test_03_scenario_2_topic_filtering_python_loops(self):
        """Upload multi-chapter PDF, filter topic specifically for 'Python Loops'."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token_a = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token_a}"}

        pdf_path = os.path.join(ROOT_DIR, "sample_data", "Machine_Learning_Notes.pdf")
        with open(pdf_path, "rb") as f:
            data = {
                "file": (f, "Machine_Learning_Notes.pdf"),
                "topic": "Python Loops",
                "num_questions": 5,
                "difficulty": "medium",
                "question_types": json.dumps(["mcq", "true_false"])
            }
            res = self.client.post("/api/quizzes/generate", data=data, content_type="multipart/form-data", headers=headers)

        self.assertIn(res.status_code, (200, 201))
        quiz = res.get_json()["quiz"]
        self.assertGreaterEqual(len(quiz["questions"]), 1)

        pages = [q.get("source_page") for q in quiz["questions"]]
        self.assertIn(4, pages)

    def test_04_scenario_3_insufficient_content_guard(self):
        """Provide single trivial sentence, request 50 questions -> verify guard."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token_a = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token_a}"}

        short_notes = "Supervised learning uses labeled data."
        payload = {
            "text": short_notes,
            "topic": "Short Note",
            "num_questions": 50,
            "difficulty": "difficult",
            "question_types": ["mcq"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 200)
        data = res.get_json()
        self.assertTrue(data.get("insufficient_content"))

    def test_05_scenario_4_multi_user_data_isolation(self):
        """Verify User B cannot access User A's materials or quizzes."""
        reg_b = {
            "name": "Bob Smith",
            "email": "bob.test@university.edu",
            "password": "password456",
            "confirm_password": "password456",
            "role": "student"
        }
        self.client.post("/api/auth/register", json=reg_b)
        
        res_b = self.client.post("/api/auth/login", json={"email": "bob.test@university.edu", "password": "password456"})
        token_b = res_b.get_json()["token"]

        res = self.client.get("/api/materials", headers={"Authorization": f"Bearer {token_b}"})
        self.assertEqual(res.status_code, 200)
        self.assertEqual(len(res.get_json()["materials"]), 0)

        res = self.client.get("/api/quizzes", headers={"Authorization": f"Bearer {token_b}"})
        self.assertEqual(res.status_code, 200)
        self.assertEqual(len(res.get_json()["quizzes"]), 0)

    def test_06_test1_topic_python_loops_10_mcqs(self):
        """TEST 1: Topic 'Python Loops' -> 10 MCQs."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "topic": "  python loops  ",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        self.assertTrue(data.get("success"))
        quiz = data["quiz"]
        self.assertEqual(quiz["topic"], "Python Loops")
        self.assertEqual(len(quiz["questions"]), 10)

        loop_keywords = ["loop", "for", "while", "iteration", "break", "continue", "range", "enumerate", "zip", "nested", "pass", "iter", "next", "itertools", "generator", "infinite"]
        forbidden_keywords = ["inheritance", "polymorphism", "encapsulation", "decorator", "file handling", "django", "flask", "database", "neural"]

        for q in quiz["questions"]:
            self.assertEqual(q["type"], "mcq")
            self.assertEqual(len(q["options"]), 4)
            self.assertIn(q["correct_answer"], q["options"])
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q['options'])} {q['explanation']}".lower()

            has_loop_concept = any(k in q_full for k in loop_keywords)
            self.assertTrue(has_loop_concept, f"Question should be about Python loops: {q['question']}")

            for f in forbidden_keywords:
                self.assertNotIn(f, q["question"].lower(), f"Question should not contain unrelated concept '{f}': {q['question']}")

    def test_07_test2_topic_dbms_transactions_10_questions(self):
        """TEST 2: Topic 'DBMS Transactions' -> 10 questions."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "topic": "DBMS Transactions and ACID Properties",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq", "true_false", "short_answer"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        quiz = data["quiz"]
        self.assertEqual(quiz["topic"], "DBMS Transactions and ACID Properties")
        self.assertEqual(len(quiz["questions"]), 10)

        txn_keywords = ["transaction", "acid", "atomicity", "consistency", "isolation", "durability", "commit", "rollback", "savepoint", "concurrency", "schedule", "serializability", "lock", "2pl", "deadlock", "wal", "log", "read"]
        for q in quiz["questions"]:
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q.get('options', []))} {q.get('explanation', '')}".lower()
            has_txn_concept = any(k in q_full for k in txn_keywords)
            self.assertTrue(has_txn_concept, f"Question should be about DBMS Transactions: {q['question']}")

    def test_08_test3_topic_machine_learning_10_questions(self):
        """TEST 3: Topic 'Machine Learning' -> 10 questions."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "topic": "Machine Learning",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq", "true_false", "short_answer"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        quiz = data["quiz"]
        self.assertEqual(len(quiz["questions"]), 10)

        ml_keywords = ["model", "learning", "supervised", "unsupervised", "regression", "classification", "loss", "gradient", "overfitting", "variance", "bias", "metric", "f1", "precision", "recall", "validation", "clustering", "pca"]
        for q in quiz["questions"]:
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q.get('options', []))} {q.get('explanation', '')}".lower()
            has_ml_concept = any(k in q_full for k in ml_keywords)
            self.assertTrue(has_ml_concept, f"Question should be about Machine Learning: {q['question']}")

    def test_09_test5_flashcards_end_to_end(self):
        """TEST 5: Flashcards for 'Python Loops' end-to-end."""
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token_a = res.get_json()["token"]
        headers_a = {"Authorization": f"Bearer {token_a}"}

        fc_payload = {
            "topic": "  python loops  ",
            "num_cards": 10
        }
        res = self.client.post("/api/flashcards/generate", json=fc_payload, headers=headers_a)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        self.assertTrue(data.get("success"))

        deck = data["deck"]
        deck_id = deck["id"]
        cards = deck["cards"]
        self.assertEqual(len(cards), 10)
        self.assertEqual(deck["topic"], "Python Loops")

        # GET /api/flashcards
        res_list = self.client.get("/api/flashcards", headers=headers_a)
        self.assertEqual(res_list.status_code, 200)

        # GET /api/flashcards/<id>
        res_get = self.client.get(f"/api/flashcards/{deck_id}", headers=headers_a)
        self.assertEqual(res_get.status_code, 200)

        # PUT /api/flashcards/<deck_id>/cards/<card_id>
        first_card_id = cards[0]["id"]
        res_update = self.client.put(
            f"/api/flashcards/{deck_id}/cards/{first_card_id}",
            json={"mastered": True, "difficulty_rating": "easy"},
            headers=headers_a
        )
        self.assertEqual(res_update.status_code, 200)

        # User B isolation
        res_b = self.client.post("/api/auth/login", json={"email": "bob.test@university.edu", "password": "password456"})
        token_b = res_b.get_json()["token"]
        headers_b = {"Authorization": f"Bearer {token_b}"}

        res_b_list = self.client.get("/api/flashcards", headers=headers_b)
        self.assertEqual(len(res_b_list.get_json()["decks"]), 0)

        # Delete Deck
        res_del = self.client.delete(f"/api/flashcards/{deck_id}", headers=headers_a)
        self.assertEqual(res_del.status_code, 200)

    def test_10_article_climate_change_10_questions(self):
        """
        ARTICLE TEST 1 (from Requirements):
        Input Type: Article / Notes
        Topic: Climate Change
        Questions: 10
        Types: MCQ + True/False + Short Answer
        Difficulty: Mixed (medium)
        Verify exactly 10 questions generated and relevant to Climate Change.
        """
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "text": CLIMATE_CHANGE_ARTICLE,
            "topic": "Climate Change",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq", "true_false", "short_answer"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        self.assertTrue(data.get("success"))
        self.assertIn("quiz", data)
        quiz = data["quiz"]
        self.assertEqual(quiz["topic"], "Climate Change")
        self.assertEqual(len(quiz["questions"]), 10)

        q_types_present = set(q["type"] for q in quiz["questions"])
        self.assertTrue(len(q_types_present) >= 2, "Quiz should contain mixed question types")

        # Verify questions are grounded and relevant to Climate Change
        climate_terms = ["climate", "change", "global", "warming", "greenhouse", "gas", "emission", "carbon", "methane", "fossil", "fuel", "deforestation", "temperature", "drought", "flood", "sea", "ice", "renewable", "solar", "wind", "biodiversity"]
        for q in quiz["questions"]:
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q.get('options', []))} {q.get('explanation', '')}".lower()
            has_climate_term = any(t in q_full for t in climate_terms)
            self.assertTrue(has_climate_term, f"Question should be relevant to Climate Change: {q['question']}")

        print(f"\n[Article Test 1 Passed] Generated 10 valid questions for 'Climate Change' from Article.")

    def test_11_article_greenhouse_gases_topic(self):
        """
        ARTICLE TEST 2 (from Requirements):
        Same article, Topic: 'Greenhouse Gases'.
        Questions: 10.
        Verify questions focus on greenhouse gases and related concepts from the article.
        """
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "text": CLIMATE_CHANGE_ARTICLE,
            "topic": "Greenhouse Gases",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq", "true_false", "short_answer"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        quiz = data["quiz"]
        self.assertEqual(len(quiz["questions"]), 10)

        # Verify questions are on Greenhouse Gases & related domain
        ghg_terms = ["greenhouse", "gas", "carbon", "methane", "emission", "fossil", "fuel", "atmosphere", "heat", "temperature", "climate", "deforestation", "agriculture", "energy", "solar", "co2"]
        for q in quiz["questions"]:
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q.get('options', []))} {q.get('explanation', '')}".lower()
            has_ghg_term = any(t in q_full for t in ghg_terms)
            self.assertTrue(has_ghg_term, f"Question should be relevant to Greenhouse Gases: {q['question']}")

        print(f"\n[Article Test 2 Passed] Generated 10 valid questions for 'Greenhouse Gases' from Article.")

    def test_12_article_effects_of_climate_change_topic(self):
        """
        ARTICLE TEST 3 (from Requirements):
        Same article, Topic: 'Effects of Climate Change'.
        Questions: 10.
        Questions should focus on effects (temperatures, heat waves, rainfall, melting glaciers, sea-level rise, droughts, flooding, biodiversity).
        """
        res = self.client.post("/api/auth/login", json={"email": "alice.test@university.edu", "password": "password123"})
        token = res.get_json()["token"]
        headers = {"Authorization": f"Bearer {token}"}

        payload = {
            "text": CLIMATE_CHANGE_ARTICLE,
            "topic": "Effects of Climate Change",
            "num_questions": 10,
            "difficulty": "medium",
            "question_types": ["mcq", "true_false", "short_answer"]
        }
        res = self.client.post("/api/quizzes/generate", json=payload, headers=headers)
        self.assertEqual(res.status_code, 201)
        data = res.get_json()
        quiz = data["quiz"]
        self.assertEqual(len(quiz["questions"]), 10)

        effects_terms = ["drought", "heat", "temperature", "rainfall", "precipitation", "glacier", "ice", "sea", "flood", "biodiversity", "impact", "weather", "wildfire", "consequence", "agriculture", "crop", "storm", "shift", "warming", "climate"]
        for q in quiz["questions"]:
            q_full = f"{q['question']} {q['correct_answer']} {' '.join(q.get('options', []))} {q.get('explanation', '')}".lower()
            has_effect_term = any(t in q_full for t in effects_terms)
            self.assertTrue(has_effect_term, f"Question should be relevant to Effects of Climate Change: {q['question']}")

        print(f"\n[Article Test 3 Passed] Generated 10 valid questions for 'Effects of Climate Change' from Article.")

if __name__ == "__main__":
    unittest.main()
